name: mith static ci

on: [push, pull_request]

jobs:
  build:
    name: mith-static tests
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2

      - name: run tests
        run: |
          curl -L https://deno.land/x/install/install.sh | sh -s "v1.2.2"
          export PATH="$HOME/.deno/bin:$PATH"
          deno test --allow-net --allow-read --allow-env